import 'package:medinven/features/sales/domain/entities/sales_entity.dart';

class Sales {
  static List<SalesEntity> invenList = [
    SalesEntity(
        customerName: 'Atanu Sabyasachi',
        customerPhone: 7008183804,
        medicineName: 'Meftalspas',
        medicineType: 'Strips',
        saleDate: DateTime(2022, 03, 13),
        doctorName: 'Barsha Das',
        invoiceNumber: 'sv2iy3hvs2',
        prescription: '',
        finalDiscount: 20,
        totalProfit: 50,
        comment: '',
        quantity: 10,
        discount: 20,
        mrp: 150,
        gst: 5,
        batchCode: 'bjxjb3jb',
        expiryDate: DateTime(2024, 12, 04),
        marginLeft: ''),
    SalesEntity(
        customerName: 'Amrut Abhishek Swain',
        customerPhone: 7008183804,
        medicineName: 'Absolute Woman',
        medicineType: 'Strips',
        saleDate: DateTime(2022, 03, 13),
        doctorName: 'Barsha Das',
        invoiceNumber: 'sv2iy3hvs2',
        prescription: '',
        finalDiscount: 20,
        totalProfit: 50,
        comment: '',
        quantity: 10,
        discount: 20,
        mrp: 150,
        gst: 5,
        batchCode: 'bjxjb3jb',
        expiryDate: DateTime(2024, 12, 04),
        marginLeft: ''),
    SalesEntity(
        customerName: 'Abhishek Sahoo',
        customerPhone: 7008183804,
        medicineName: 'Meftalspas',
        medicineType: 'Strips',
        saleDate: DateTime(2022, 03, 13),
        doctorName: 'Barsha Das',
        invoiceNumber: 'sv2iy3hvs2',
        prescription: '',
        finalDiscount: 20,
        totalProfit: 50,
        comment: '',
        quantity: 10,
        discount: 20,
        mrp: 150,
        gst: 5,
        batchCode: 'bjxjb3jb',
        expiryDate: DateTime(2024, 12, 04),
        marginLeft: ''),
    SalesEntity(
        customerName: 'Soubhagya Mohanty',
        customerPhone: 7008183804,
        medicineName: 'Meftalspas',
        medicineType: 'Strips',
        saleDate: DateTime(2022, 03, 13),
        doctorName: 'Barsha Das',
        invoiceNumber: 'sv2iy3hvs2',
        prescription: '',
        finalDiscount: 20,
        totalProfit: 50,
        comment: '',
        quantity: 10,
        discount: 20,
        mrp: 150,
        gst: 5,
        batchCode: 'bjxjb3jb',
        expiryDate: DateTime(2024, 12, 04),
        marginLeft: ''),
  ];
}
